# defaultContentLanguage = "en"
# languageCode = "en-us"
# defaultContentLanguageInSubdir = true
baseURL = "https://www.angularcorp.com/" # Must end with splash
languageCode = "en-us"
title = "{Pacific Hackers} - Discover Issues, Share Solutions."
# disqusShortname = "yourDisqusShortname"
# contentDir = "content"

staticDir = ["static", "themes/Niello/static"]

theme = "Niello"

 [languages]
	[languages.en]
		title = "./Pacific Hackers - Alone We Are Strong, Together We Are Unstoppable"
		languageCode = "en-us"
		LanguageName = "ğŸ‡ºğŸ‡¸EN"
		contentDir = "content"
		weight = 1
		[[languages.en.menus.main]]
			name = 'Home'
			pageRef = '/'
			weight = 1
		[[languages.en.menus.main]]
			name = 'Categories'
			pageRef = '/categories'
			weight = 2
		[[languages.en.menus.main]]
			name = 'Tags'
			pageRef = '/tags'
			weight = 3
		[[languages.en.menus.main]]
			name = 'Contact'
			pageRef = '/contact'
			weight = 4
#	[languages.zh]
#		title = "{ç é€”è½¨è¿¹} - å‘ç°é—®é¢˜ï¼Œåˆ†äº«è§£å†³."
#        languageCode = "zh-cn"
#        LanguageName = "ğŸ‡¨ğŸ‡³CN"
#        contentDir = "content/zh"
#        weight = 2
#		[[languages.zh.menus.main]]
#			name = 'é¦–é¡µ'
#			pageRef = '/'
#			weight = 1
#		[[languages.zh.menus.main]]
#			name = 'æ–‡ç« åˆ†ç±»'
#			pageRef = '/categories'
#			weight = 2
#		[[languages.zh.menus.main]]
#			name = 'æ ‡ç­¾'
#			pageRef = '/tags'
#			weight = 3
#		[[languages.zh.menus.main]]
#			name = 'è”ç³»æˆ‘ä»¬'
#			pageRef = '/contact'
#			weight = 4
        
[params]
keywords = "" 
description = "" 
copyright = "&#xA9; 2024 Pacific Hackers Assosciation. All Rights Reserved."
# google_ad_client = "ca-pub-******" 
# ga4 = "G-******"
# sharethis = "" 

[outputs]
  home = ["HTML", "JSON"]
    